package com.example.lab1.mybatis.dao;

import com.example.lab1.mybatis.model.Group;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    List<Group> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    int updateByPrimaryKey(Group record);
}