package com.example.lab1.mybatis.model;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_.ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_.COURSE
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    private Integer course;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_.ID
     *
     * @return the value of PUBLIC.GROUP_.ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_.ID
     *
     * @param id the value for PUBLIC.GROUP_.ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_.COURSE
     *
     * @return the value of PUBLIC.GROUP_.COURSE
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public Integer getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_.COURSE
     *
     * @param course the value for PUBLIC.GROUP_.COURSE
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public void setCourse(Integer course) {
        this.course = course;
    }
}