package com.example.lab1.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @return the value of PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @param surname the value for PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @return the value of PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @param groupId the value for PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Tue Apr 05 19:54:11 EEST 2022
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}