package com.example.lab1.mybatis.model;

public class StudentCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.STUDENTS_ID
     *
     * @mbg.generated Wed Apr 06 15:52:32 EEST 2022
     */
    private Integer studentsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.COURSES_ID
     *
     * @mbg.generated Wed Apr 06 15:52:32 EEST 2022
     */
    private Long coursesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.STUDENTS_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.STUDENTS_ID
     *
     * @mbg.generated Wed Apr 06 15:52:32 EEST 2022
     */
    public Integer getStudentsId() {
        return studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.STUDENTS_ID
     *
     * @param studentsId the value for PUBLIC.STUDENT_COURSE.STUDENTS_ID
     *
     * @mbg.generated Wed Apr 06 15:52:32 EEST 2022
     */
    public void setStudentsId(Integer studentsId) {
        this.studentsId = studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.COURSES_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.COURSES_ID
     *
     * @mbg.generated Wed Apr 06 15:52:32 EEST 2022
     */
    public Long getCoursesId() {
        return coursesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.COURSES_ID
     *
     * @param coursesId the value for PUBLIC.STUDENT_COURSE.COURSES_ID
     *
     * @mbg.generated Wed Apr 06 15:52:32 EEST 2022
     */
    public void setCoursesId(Long coursesId) {
        this.coursesId = coursesId;
    }
}